/** Auto-generated by scripts/build-recruitment-data.mjs — do not edit. */

import type { ContractorTypeId, ResourceCost } from "./types";

export interface RecruitmentUnitDefinition {
  name: string;
  contractorType: ContractorTypeId;
  tier: number;
  cost: ResourceCost;
  flavorTitle: string;
  description: string;
}

export const RECRUITMENT_UNITS: RecruitmentUnitDefinition[] = [
  {
    "name": "Fresh Graduate",
    "contractorType": "farming",
    "tier": 1,
    "cost": {
      "cash": 20,
      "reputation": 1
    },
    "flavorTitle": "Eager, cheap, knows nothing",
    "description": "Very cheap, high availability, low fatigue gain"
  },
  {
    "name": "Part-timer",
    "contractorType": "farming",
    "tier": 1,
    "cost": {
      "cash": 25,
      "reputation": 2
    },
    "flavorTitle": "Can be sent on short or awkward-hour jobs without complaining.",
    "description": "Flexible schedule, low commitment cost."
  },
  {
    "name": "Office clerk",
    "contractorType": "farming",
    "tier": 2,
    "cost": {
      "cash": 50,
      "reputation": 3
    },
    "flavorTitle": "Has survived at least one real job",
    "description": "Decent all-rounder, better success rate"
  },
  {
    "name": "Call Center Veteran",
    "contractorType": "farming",
    "tier": 2,
    "cost": {
      "cash": 70,
      "reputation": 3
    },
    "flavorTitle": "Has heard every customer scream",
    "description": "High tolerance for soul-crushing work, good on phone/service jobs"
  },
  {
    "name": "Mall Cop",
    "contractorType": "defense",
    "tier": 1,
    "cost": {
      "cash": 95,
      "supply": 30
    },
    "flavorTitle": "High visibility, low authority",
    "description": "Cheap deterrence, reduces minor disturbance chance"
  },
  {
    "name": "Night Watchman",
    "contractorType": "defense",
    "tier": 1,
    "cost": {
      "cash": 95,
      "supply": 60
    },
    "flavorTitle": "Sleeps with one eye open (sometimes)",
    "description": "Good at passive guarding, low upkeep"
  },
  {
    "name": "Ex-bouncer",
    "contractorType": "defense",
    "tier": 2,
    "cost": {
      "cash": 195,
      "supply": 100
    },
    "flavorTitle": "Used to actual trouble",
    "description": "Solid against street-level gangs, intimidation bonus"
  },
  {
    "name": "Corporate Security",
    "contractorType": "defense",
    "tier": 2,
    "cost": {
      "cash": 295,
      "supply": 300
    },
    "flavorTitle": "Has a radio and a slightly better vest",
    "description": "Better all-round protection, small bonus on official contracts"
  },
  {
    "name": "Internet surfer",
    "contractorType": "intel",
    "tier": 1,
    "cost": {
      "cash": 110,
      "supply": 100,
      "connection": 4
    },
    "flavorTitle": "Lives on forums and free Wi-Fi",
    "description": "Cheap basic intel, finds public job info"
  },
  {
    "name": "Office Gossip",
    "contractorType": "intel",
    "tier": 1,
    "cost": {
      "cash": 110,
      "supply": 100,
      "connection": 4
    },
    "flavorTitle": "Hears everything by the water cooler",
    "description": "Good at local/soft intel, morale side benefits"
  },
  {
    "name": "LinkedIn Stalker",
    "contractorType": "intel",
    "tier": 2,
    "cost": {
      "cash": 110,
      "supply": 100,
      "connection": 4
    },
    "flavorTitle": "Professional-grade creeping",
    "description": "Accurate client & rival info, better bid intel"
  },
  {
    "name": "Data Entry Snoop",
    "contractorType": "intel",
    "tier": 2,
    "cost": {
      "cash": 110,
      "supply": 100,
      "connection": 4
    },
    "flavorTitle": "Notices things while doing boring work",
    "description": "Passive intel while assigned to normal jobs"
  },
  {
    "name": "Janitor",
    "contractorType": "support",
    "tier": 1,
    "cost": {
      "cash": 150,
      "supply": 100
    },
    "flavorTitle": "Sees everything, judged by no one",
    "description": "Small passive recovery bonus, tiny chance to prevent incidents"
  },
  {
    "name": "Bike Courier",
    "contractorType": "support",
    "tier": 1,
    "cost": {
      "cash": 550,
      "supply": 200,
      "reputation": 5
    },
    "flavorTitle": "Moves things and sometimes people",
    "description": "Speeds up job start / supply delivery, small mobility bonus"
  },
  {
    "name": "Junior Team Lead",
    "contractorType": "support",
    "tier": 2,
    "cost": {
      "cash": 1550,
      "supply": 200,
      "reputation": 15
    },
    "flavorTitle": "Was promoted for surviving longest",
    "description": "Gives yield / success bonus to a small team"
  },
  {
    "name": "Office Mom/Dad",
    "contractorType": "support",
    "tier": 2,
    "cost": {
      "cash": 1000,
      "supply": 200,
      "reputation": 15
    },
    "flavorTitle": "Emotional support + snacks",
    "description": "Strong fatigue recovery bonus, morale boost"
  }
];

/** Tier-1 hire cost per contractor type (from sheet). */
export const RECRUITMENT_TIER1_COST: Record<ContractorTypeId, ResourceCost> = {
  "farming": {
    "cash": 20,
    "reputation": 1
  },
  "defense": {
    "cash": 95,
    "supply": 30
  },
  "intel": {
    "cash": 110,
    "supply": 100,
    "connection": 4
  },
  "support": {
    "cash": 150,
    "supply": 100
  }
};

export const RECRUITMENT_TIER1_LABEL: Record<ContractorTypeId, string> = {
  "farming": "Fresh Graduate",
  "defense": "Mall Cop",
  "intel": "Internet surfer",
  "support": "Janitor"
};
