/** Auto-generated by scripts/build-recruitment-data.mjs — do not edit. */

import type { ContractorCategoryId, ResourceCost, UnitId } from "./types";

export interface RecruitmentUnitDefinition {
  id: UnitId;
  name: string;
  category: ContractorCategoryId;
  tier: number;
  cost: ResourceCost;
  detail: string;
  proposedRole: string;
}

export const RECRUITMENT_UNITS: RecruitmentUnitDefinition[] = [
  {
    "id": "fresh_graduate",
    "name": "Fresh Graduate",
    "category": "farming",
    "tier": 1,
    "cost": {
      "cash": 20,
      "reputation": 1
    },
    "detail": "Very cheap, high availability, low fatigue gain",
    "proposedRole": "Cheapest crew. -15% payout on jobs unless crew size is above optimal. Low commitment cost; good filler unit."
  },
  {
    "id": "part_timer",
    "name": "Part-timer",
    "category": "farming",
    "tier": 1,
    "cost": {
      "cash": 25,
      "reputation": 2
    },
    "detail": "Flexible schedule, low commitment cost.",
    "proposedRole": "-10% contract duration on short jobs (below median duration). No bonus on long or awkward-hour jobs."
  },
  {
    "id": "office_clerk",
    "name": "Office clerk",
    "category": "farming",
    "tier": 2,
    "cost": {
      "cash": 50,
      "reputation": 3
    },
    "detail": "Decent all-rounder, better success rate",
    "proposedRole": "Baseline professional farming unit: no tier-1 penalty, +5% payout vs average tier-1 farming crew."
  },
  {
    "id": "call_center_veteran",
    "name": "Call Center Veteran",
    "category": "farming",
    "tier": 2,
    "cost": {
      "cash": 70,
      "reputation": 3
    },
    "detail": "High tolerance for soul-crushing work, good on phone/service jobs",
    "proposedRole": "+10% payout on service/client-facing contracts. Resistant to mood drain while on jobs."
  },
  {
    "id": "mall_cop",
    "name": "Mall Cop",
    "category": "defense",
    "tier": 1,
    "cost": {
      "cash": 95,
      "supply": 30
    },
    "detail": "Cheap deterrence, reduces minor disturbance chance",
    "proposedRole": "-5% minor incident chance (future event system). +3% espionage defense per unit."
  },
  {
    "id": "night_watchman",
    "name": "Night Watchman",
    "category": "defense",
    "tier": 1,
    "cost": {
      "cash": 95,
      "supply": 60
    },
    "detail": "Good at passive guarding, low upkeep",
    "proposedRole": "Passive office guard: +4% espionage defense without assignment. Lower upkeep profile."
  },
  {
    "id": "ex_bouncer",
    "name": "Ex-bouncer",
    "category": "defense",
    "tier": 2,
    "cost": {
      "cash": 195,
      "supply": 100
    },
    "detail": "Solid against street-level gangs, intimidation bonus",
    "proposedRole": "Street-threat specialist: +8% espionage defense. On high-risk contracts, -10% failure risk when assigned."
  },
  {
    "id": "corporate_security",
    "name": "Corporate Security",
    "category": "defense",
    "tier": 2,
    "cost": {
      "cash": 295,
      "supply": 300
    },
    "detail": "Better all-round protection, small bonus on official contracts",
    "proposedRole": "Generalist protection: +6% espionage defense. +5% payout safety bonus on official/gov-tagged contracts."
  },
  {
    "id": "internet_surfer",
    "name": "Internet surfer",
    "category": "intel",
    "tier": 1,
    "cost": {
      "cash": 110,
      "supply": 100,
      "connection": 4
    },
    "detail": "Cheap basic intel, finds public job info",
    "proposedRole": "1.0 intel point for project unlock math. Unlocks basic public contract intel."
  },
  {
    "id": "office_gossip",
    "name": "Office Gossip",
    "category": "intel",
    "tier": 1,
    "cost": {
      "cash": 110,
      "supply": 100,
      "connection": 4
    },
    "detail": "Good at local/soft intel, morale side benefits",
    "proposedRole": "0.8 intel points, but +0.02 mood/hr passive while stationed at office."
  },
  {
    "id": "linkedin_stalker",
    "name": "LinkedIn Stalker",
    "category": "intel",
    "tier": 2,
    "cost": {
      "cash": 110,
      "supply": 100,
      "connection": 4
    },
    "detail": "Accurate client & rival info, better bid intel",
    "proposedRole": "1.5 intel points. Phase 2: improves bid visibility and rival intel (reduces hidden bid penalty)."
  },
  {
    "id": "data_entry_snoop",
    "name": "Data Entry Snoop",
    "category": "intel",
    "tier": 2,
    "cost": {
      "cash": 110,
      "supply": 100,
      "connection": 4
    },
    "detail": "Passive intel while assigned to normal jobs",
    "proposedRole": "0.5 intel at office, plus +0.3 intel per farming unit deployed on the active contract."
  },
  {
    "id": "janitor",
    "name": "Janitor",
    "category": "support",
    "tier": 1,
    "cost": {
      "cash": 150,
      "supply": 100
    },
    "detail": "Small passive recovery bonus, tiny chance to prevent incidents",
    "proposedRole": "Office passive: +0.01 mood/hr per unit. 1% incident-prevention roll (future event system)."
  },
  {
    "id": "bike_courier",
    "name": "Bike Courier",
    "category": "support",
    "tier": 1,
    "cost": {
      "cash": 550,
      "supply": 200,
      "reputation": 5
    },
    "detail": "Speeds up job start / supply delivery, small mobility bonus",
    "proposedRole": "Mission attach: -8% contract duration. Staff transfers arrive 1 hex sooner (rounded)."
  },
  {
    "id": "junior_team_lead",
    "name": "Junior Team Lead",
    "category": "support",
    "tier": 2,
    "cost": {
      "cash": 1550,
      "supply": 200,
      "reputation": 15
    },
    "detail": "Gives yield / success bonus to a small team",
    "proposedRole": "Mission attach: +8% payout for up to 3 farming units assigned to the same contract."
  },
  {
    "id": "office_mom_dad",
    "name": "Office Mom/Dad",
    "category": "support",
    "tier": 2,
    "cost": {
      "cash": 1000,
      "supply": 200,
      "reputation": 15
    },
    "detail": "Strong fatigue recovery bonus, morale boost",
    "proposedRole": "Office or mission: +0.03 mood/hr at site. On mission, -5% duration via morale support."
  },
  {
    "id": "branch_manager",
    "name": "Branch Manager",
    "category": "special",
    "tier": 1,
    "cost": {
      "cash": 800,
      "supply": 200,
      "reputation": 10,
      "connection": 8
    },
    "detail": "Site-founding specialist. Cannot be assigned to contracts. One unit is consumed to open a branch.",
    "proposedRole": "Establish-only unit: required and consumed when founding a branch. No job or office passive effects. Further branches need Massive Expansion research + another Branch Manager each."
  }
];

export const UNIT_IDS: UnitId[] = RECRUITMENT_UNITS.map((u) => u.id);

export const DEFAULT_TIER1_UNIT: Record<ContractorCategoryId, UnitId> = {
  "farming": "fresh_graduate",
  "defense": "mall_cop",
  "intel": "internet_surfer",
  "support": "janitor",
  "special": "branch_manager"
};

/** Tier-1 hire cost per category (legacy helper). */
export const RECRUITMENT_TIER1_COST: Record<ContractorCategoryId, ResourceCost> = {
  "farming": {
    "cash": 20,
    "reputation": 1
  },
  "defense": {
    "cash": 95,
    "supply": 30
  },
  "intel": {
    "cash": 110,
    "supply": 100,
    "connection": 4
  },
  "support": {
    "cash": 150,
    "supply": 100
  },
  "special": {
    "cash": 800,
    "supply": 200,
    "reputation": 10,
    "connection": 8
  }
};

export const RECRUITMENT_TIER1_LABEL: Record<ContractorCategoryId, string> = {
  "farming": "Fresh Graduate",
  "defense": "Mall Cop",
  "intel": "Internet surfer",
  "support": "Janitor",
  "special": "Branch Manager"
};
