/** Auto-generated by scripts/build-research-data.mjs — do not edit. */

import type { ResearchDefinition } from "./types";

export const RESEARCH_DEFINITIONS: ResearchDefinition[] = [
  {
    "id": "eff_manuals_cash",
    "name": "Efficiency Manuals for $",
    "description": "Company-wide SOPs for cash handling — +5% Cash/hr from structures per level. Max +25%.",
    "category": "resources",
    "maxLevel": 5,
    "rndLevelRequired": 1,
    "baseCost": {
      "cash": 100,
      "supply": 50,
      "connection": 10,
      "mood": 0,
      "reputation": 0,
      "govReputation": 0
    },
    "costScale": 1.1,
    "buildTimeHoursPerLevel": [
      0.024,
      0.024,
      0.024,
      0.024,
      0.024
    ],
    "effects": {
      "ratePercentPerLevel": {
        "cash": 0.05
      }
    }
  },
  {
    "id": "eff_manuals_sup",
    "name": "Efficiency Manuals for SUP",
    "description": "Tighten supply closets and reorder rules — +5% SUP/hr from structures per level. Max +25%.",
    "category": "resources",
    "maxLevel": 5,
    "rndLevelRequired": 1,
    "baseCost": {
      "cash": 50,
      "supply": 100,
      "connection": 5,
      "mood": 0,
      "reputation": 0,
      "govReputation": 0
    },
    "costScale": 1.1,
    "buildTimeHoursPerLevel": [
      0.024,
      0.024,
      0.024,
      0.024,
      0.024
    ],
    "effects": {
      "ratePercentPerLevel": {
        "supply": 0.05
      }
    }
  },
  {
    "id": "eff_manuals_con",
    "name": "Efficiency Manuals for CON",
    "description": "Networking playbooks for client outreach — +5% Connection/hr from structures per level. Max +25%.",
    "category": "resources",
    "maxLevel": 5,
    "rndLevelRequired": 5,
    "baseCost": {
      "cash": 200,
      "supply": 200,
      "connection": 50,
      "mood": 0,
      "reputation": 0,
      "govReputation": 0
    },
    "costScale": 1.1,
    "buildTimeHoursPerLevel": [
      0.036000000000000004,
      0.036000000000000004,
      0.036000000000000004,
      0.036000000000000004,
      0.036000000000000004
    ],
    "effects": {
      "ratePercentPerLevel": {
        "connection": 0.05
      }
    }
  },
  {
    "id": "eff_manuals_mood",
    "name": "Efficiency Manuals for Mood",
    "description": "Morale guides for break-room culture — +5% Mood/hr from structures per level. Max +25%.",
    "category": "resources",
    "maxLevel": 5,
    "rndLevelRequired": 5,
    "baseCost": {
      "cash": 200,
      "supply": 200,
      "connection": 50,
      "mood": 0,
      "reputation": 0,
      "govReputation": 0
    },
    "costScale": 1.1,
    "buildTimeHoursPerLevel": [
      0.036000000000000004,
      0.036000000000000004,
      0.036000000000000004,
      0.036000000000000004,
      0.036000000000000004
    ],
    "effects": {
      "ratePercentPerLevel": {
        "mood": 0.05
      }
    }
  },
  {
    "id": "eff_manuals_rep",
    "name": "Efficiency Manuals REP",
    "description": "PR templates and stakeholder maps — +5% REP/hr from structures per level. Max +25%.",
    "category": "resources",
    "maxLevel": 5,
    "rndLevelRequired": 6,
    "baseCost": {
      "cash": 400,
      "supply": 400,
      "connection": 100,
      "mood": 0,
      "reputation": 10,
      "govReputation": 10
    },
    "costScale": 1.1,
    "buildTimeHoursPerLevel": [
      0.12,
      0.12,
      0.12,
      0.12,
      0.12
    ],
    "effects": {
      "ratePercentPerLevel": {
        "reputation": 0.05
      }
    }
  },
  {
    "id": "eff_manuals_grep",
    "name": "Efficiency Manuals GREP",
    "description": "Government liaison procedures — +5% GREP/hr from structures per level. Max +25%.",
    "category": "resources",
    "maxLevel": 5,
    "rndLevelRequired": 6,
    "baseCost": {
      "cash": 400,
      "supply": 400,
      "connection": 100,
      "mood": 0,
      "reputation": 10,
      "govReputation": 10
    },
    "costScale": 1.1,
    "buildTimeHoursPerLevel": [
      0.12,
      0.12,
      0.12,
      0.12,
      0.12
    ],
    "effects": {
      "ratePercentPerLevel": {
        "govReputation": 0.05
      }
    }
  },
  {
    "id": "planning_ahead",
    "name": "Planning ahead",
    "description": "Forecast storage needs before the next shipment — +3% Cash and SUP caps per level. Max +15%.",
    "category": "resources",
    "maxLevel": 5,
    "rndLevelRequired": 2,
    "baseCost": {
      "cash": 100,
      "supply": 50,
      "connection": 10,
      "mood": 0,
      "reputation": 0,
      "govReputation": 0
    },
    "costScale": 1.1,
    "buildTimeHoursPerLevel": [
      0.24,
      0.24,
      0.24,
      0.24,
      0.24
    ],
    "requires": [
      {
        "id": "eff_manuals_cash",
        "minLevel": 3
      },
      {
        "id": "eff_manuals_sup",
        "minLevel": 3
      }
    ],
    "effects": {
      "storagePercentPerLevel": 0.03
    }
  },
  {
    "id": "branch_management",
    "name": "Branch Management",
    "description": "Train branch leads and open your first remote office from a commercial lot.",
    "category": "unlock",
    "maxLevel": 1,
    "rndLevelRequired": 6,
    "baseCost": {
      "cash": 200,
      "supply": 400,
      "connection": 100,
      "mood": 0,
      "reputation": 0,
      "govReputation": 0
    },
    "costScale": 1.1,
    "buildTimeHoursPerLevel": [
      0.24
    ],
    "effects": {}
  },
  {
    "id": "bid_modeling",
    "name": "Bid Modeling",
    "description": "Spreadsheet models for tower bids — +4% cash payout on projects per level. Max +20%.",
    "category": "mult",
    "maxLevel": 5,
    "rndLevelRequired": 1,
    "baseCost": {
      "cash": 100,
      "supply": 100,
      "connection": 100,
      "mood": 0,
      "reputation": 0,
      "govReputation": 0
    },
    "costScale": 1.1,
    "buildTimeHoursPerLevel": [
      0.8400000000000001,
      0.8400000000000001,
      0.8400000000000001,
      0.8400000000000001,
      0.8400000000000001
    ],
    "requires": [
      {
        "id": "eff_manuals_con",
        "minLevel": 1
      }
    ],
    "effects": {
      "projectPayoutMultPerLevel": 0.04
    }
  },
  {
    "id": "discover_video_studio",
    "name": "Discover: Video production studio",
    "description": "Scout a site plan for a video studio — adds the build to your Office tab.",
    "category": "discover",
    "maxLevel": 1,
    "rndLevelRequired": 1,
    "baseCost": {
      "cash": 100,
      "supply": 100,
      "connection": 100,
      "mood": 0,
      "reputation": 0,
      "govReputation": 0
    },
    "costScale": 1.1,
    "buildTimeHoursPerLevel": [
      0.024
    ],
    "effects": {
      "unlocksStructure": "video_production_studio"
    }
  },
  {
    "id": "discover_press_room",
    "name": "Discover: Press Room",
    "description": "Scout a site plan for a press room — adds the build to your Office tab.",
    "category": "discover",
    "maxLevel": 1,
    "rndLevelRequired": 1,
    "baseCost": {
      "cash": 110,
      "supply": 100,
      "connection": 100,
      "mood": 0,
      "reputation": 0,
      "govReputation": 0
    },
    "costScale": 1.1,
    "buildTimeHoursPerLevel": [
      0.024
    ],
    "effects": {
      "unlocksStructure": "press_room"
    }
  },
  {
    "id": "discover_company_statue",
    "name": "Discover: Company Statue",
    "description": "Scout a site plan for a company statue — adds the build to your Office tab.",
    "category": "discover",
    "maxLevel": 1,
    "rndLevelRequired": 1,
    "baseCost": {
      "cash": 120,
      "supply": 100,
      "connection": 100,
      "mood": 0,
      "reputation": 0,
      "govReputation": 0
    },
    "costScale": 1.1,
    "buildTimeHoursPerLevel": [
      0.024
    ],
    "effects": {
      "unlocksStructure": "company_statue"
    }
  },
  {
    "id": "discover_electricity_generator",
    "name": "Discover: Electricity Generator",
    "description": "Scout a site plan for a an electricity generator — adds the build to your Office tab.",
    "category": "discover",
    "maxLevel": 1,
    "rndLevelRequired": 2,
    "baseCost": {
      "cash": 130,
      "supply": 100,
      "connection": 100,
      "mood": 0,
      "reputation": 0,
      "govReputation": 0
    },
    "costScale": 1.1,
    "buildTimeHoursPerLevel": [
      0.024
    ],
    "effects": {
      "unlocksStructure": "electricity_generator"
    }
  },
  {
    "id": "discover_mit_room",
    "name": "Discover: MIT (Management in training) room",
    "description": "Scout a site plan for a management training room — adds the build to your Office tab.",
    "category": "discover",
    "maxLevel": 1,
    "rndLevelRequired": 2,
    "baseCost": {
      "cash": 140,
      "supply": 100,
      "connection": 100,
      "mood": 0,
      "reputation": 0,
      "govReputation": 0
    },
    "costScale": 1.1,
    "buildTimeHoursPerLevel": [
      0.024
    ],
    "effects": {
      "unlocksStructure": "mit_room"
    }
  },
  {
    "id": "portfolio_management",
    "name": "Portfolio Management",
    "description": "Run more jobs at once — +1 concurrent task force per level (base cap 3).",
    "category": "unlock",
    "maxLevel": 2,
    "rndLevelRequired": 2,
    "baseCost": {
      "cash": 100,
      "supply": 50,
      "connection": 10,
      "mood": 0,
      "reputation": 0,
      "govReputation": 0
    },
    "costScale": 1.1,
    "buildTimeHoursPerLevel": [
      0.024,
      0.024
    ],
    "requires": [
      {
        "id": "planning_ahead",
        "minLevel": 1
      }
    ],
    "effects": {
      "engagementCapPerLevel": 1
    }
  },
  {
    "id": "massive_expansion",
    "name": "Massive Expansion",
    "description": "Scale the branch network — +1 branch office slot per level beyond your first.",
    "category": "unlock",
    "maxLevel": 4,
    "rndLevelRequired": 8,
    "baseCost": {
      "cash": 1200,
      "supply": 800,
      "connection": 200,
      "mood": 0,
      "reputation": 20,
      "govReputation": 10
    },
    "costScale": 1.15,
    "buildTimeHoursPerLevel": [
      0.48,
      0.48,
      0.48,
      0.48
    ],
    "requires": [
      {
        "id": "branch_management",
        "minLevel": 1
      }
    ],
    "effects": {
      "branchSlotPerLevel": 1
    }
  }
];
