/** Auto-generated by scripts/build-research-data.mjs — do not edit. */

import type { ResearchDefinition } from "./types";

export const RESEARCH_DEFINITIONS: ResearchDefinition[] = [
  {
    "id": "eff_manuals_cash",
    "name": "Efficiency Manuals for $",
    "description": "5% increase in respective resources, per level",
    "maxLevel": 5,
    "rndLevelRequired": 1,
    "baseCost": {
      "cash": 100,
      "supply": 50,
      "connection": 10,
      "mood": 0,
      "reputation": 0,
      "govReputation": 0
    },
    "costScale": 1.1,
    "effects": {
      "ratePercentPerLevel": {
        "cash": 0.05
      }
    }
  },
  {
    "id": "eff_manuals_sup",
    "name": "Efficiency Manuals for SUP",
    "description": "5% increase in respective resources, per level",
    "maxLevel": 5,
    "rndLevelRequired": 1,
    "baseCost": {
      "cash": 50,
      "supply": 100,
      "connection": 5,
      "mood": 0,
      "reputation": 0,
      "govReputation": 0
    },
    "costScale": 1.1,
    "effects": {
      "ratePercentPerLevel": {
        "supply": 0.05
      }
    }
  },
  {
    "id": "eff_manuals_con",
    "name": "Efficiency Manuals for CON",
    "description": "5% increase in respective resources, per level",
    "maxLevel": 5,
    "rndLevelRequired": 5,
    "baseCost": {
      "cash": 200,
      "supply": 200,
      "connection": 50,
      "mood": 0,
      "reputation": 0,
      "govReputation": 0
    },
    "costScale": 1.1,
    "effects": {
      "ratePercentPerLevel": {
        "connection": 0.05
      }
    }
  },
  {
    "id": "eff_manuals_mood",
    "name": "Efficiency Manuals for Mood",
    "description": "5% increase in respective resources, per level",
    "maxLevel": 5,
    "rndLevelRequired": 5,
    "baseCost": {
      "cash": 200,
      "supply": 200,
      "connection": 50,
      "mood": 0,
      "reputation": 0,
      "govReputation": 0
    },
    "costScale": 1.1,
    "effects": {
      "ratePercentPerLevel": {
        "mood": 0.05
      }
    }
  },
  {
    "id": "eff_manuals_rep",
    "name": "Efficiency Manuals REP",
    "description": "5% increase in respective resources, per level",
    "maxLevel": 5,
    "rndLevelRequired": 6,
    "baseCost": {
      "cash": 400,
      "supply": 400,
      "connection": 100,
      "mood": 0,
      "reputation": 10,
      "govReputation": 10
    },
    "costScale": 1.1,
    "effects": {
      "ratePercentPerLevel": {
        "reputation": 0.05
      }
    }
  },
  {
    "id": "eff_manuals_grep",
    "name": "Efficiency Manuals GREP",
    "description": "5% increase in respective resources, per level",
    "maxLevel": 5,
    "rndLevelRequired": 6,
    "baseCost": {
      "cash": 400,
      "supply": 400,
      "connection": 100,
      "mood": 0,
      "reputation": 10,
      "govReputation": 10
    },
    "costScale": 1.1,
    "effects": {
      "ratePercentPerLevel": {
        "govReputation": 0.05
      }
    }
  },
  {
    "id": "planning_ahead",
    "name": "Planning ahead",
    "description": "3% increase in storage, per level",
    "maxLevel": 5,
    "rndLevelRequired": 2,
    "baseCost": {
      "cash": 100,
      "supply": 50,
      "connection": 10,
      "mood": 0,
      "reputation": 0,
      "govReputation": 0
    },
    "costScale": 1.1,
    "requires": [
      {
        "id": "eff_manuals_cash",
        "minLevel": 3
      },
      {
        "id": "eff_manuals_sup",
        "minLevel": 3
      }
    ],
    "effects": {
      "storagePercentPerLevel": 0.03
    }
  },
  {
    "id": "branch_management",
    "name": "Branch Management",
    "description": "Unlock construction of unit: Branch manager",
    "maxLevel": 1,
    "rndLevelRequired": 6,
    "baseCost": {
      "cash": 200,
      "supply": 400,
      "connection": 100,
      "mood": 0,
      "reputation": 0,
      "govReputation": 0
    },
    "costScale": 1.1,
    "effects": {}
  },
  {
    "id": "bid_modeling",
    "name": "Bid Modeling",
    "description": "Placeholder; potential idea: Unlock option to bid project; also 4% project payout on $ mult per level",
    "maxLevel": 5,
    "rndLevelRequired": 1,
    "baseCost": {
      "cash": 100,
      "supply": 100,
      "connection": 100,
      "mood": 0,
      "reputation": 0,
      "govReputation": 0
    },
    "costScale": 1.1,
    "requires": [
      {
        "id": "eff_manuals_con",
        "minLevel": 1
      }
    ],
    "effects": {
      "projectPayoutMultPerLevel": 0.04
    }
  }
];
