/** Generated by scripts/build-secretary-data.mjs — do not edit. */
import type { OfficeLocationId, SecretaryId } from "./types";

export interface SecretaryDefinition {
  id: SecretaryId;
  code: string;
  name: string;
  /** Office site where this secretary is posted. */
  officeId: OfficeLocationId;
  chiefOfStaffBonus: string;
  teamLeadBonus: string;
  /** In-world line spoken to the Director (Chief of Staff view). */
  reportLine: string;
  flavour: string[];
}

export const DEFAULT_CHIEF_OF_STAFF_ID: SecretaryId = "secretary_01";

export const SECRETARIES: SecretaryDefinition[] = [
  {
    id: "secretary_01",
    code: "Secretary_01",
    name: "Lafe",
    officeId: "hq",
    chiefOfStaffBonus: "Increase Office production by 1%",
    teamLeadBonus: "Decrease Travel time by 5%",
    reportLine: "Good morning, Director. I've cleared your morning brief and the floor is running at pace—two contracts need your sign-off when you're ready.",
    flavour: ["Lafe keeps the executive floor steady when priorities shift.","Trusted with firm-wide coordination and the details others overlook."],
  },
  {
    id: "secretary_02",
    code: "Secretary_02",
    name: "Gessesa",
    officeId: "hq",
    chiefOfStaffBonus: "Work time Decrease by 1%",
    teamLeadBonus: "Decrease Travel time by 5%",
    reportLine: "Director, I tightened today's timelines and protected your afternoon block. Say the word if you want me to pull a task force off the board.",
    flavour: ["Gessesa keeps the executive floor steady when priorities shift.","Trusted with firm-wide coordination and the details others overlook."],
  },
  {
    id: "secretary_03",
    code: "Secretary_03",
    name: "Zara",
    officeId: "hq",
    chiefOfStaffBonus: "Decrease Hiring resources cost by 1%",
    teamLeadBonus: "Decrease Travel time by 5%",
    reportLine: "Director, recruiting quotes came in under forecast. I held the vendors to our numbers—approve the roster when you want hires moving.",
    flavour: ["Zara keeps the executive floor steady when priorities shift.","Trusted with firm-wide coordination and the details others overlook."],
  },
  {
    id: "secretary_04",
    code: "Secretary_04",
    name: "Rite",
    officeId: "hq",
    chiefOfStaffBonus: "Decrease Hiring time cost by 1%",
    teamLeadBonus: "Decrease Travel time by 5%",
    reportLine: "Director, I can have the next cohort on-site Monday if you approve. I've already cut the waiting periods on our side.",
    flavour: ["Rite keeps the executive floor steady when priorities shift.","Trusted with firm-wide coordination and the details others overlook."],
  },
  {
    id: "secretary_05",
    code: "Secretary_05",
    name: "Slint",
    officeId: "hq",
    chiefOfStaffBonus: "Decrease Travel Time by 1%",
    teamLeadBonus: "Decrease Travel time by 5%",
    reportLine: "Director, task-force routes are cleaner today. Nobody stays on the road longer than they need to—I kept the board moving.",
    flavour: ["Slint keeps the executive floor steady when priorities shift.","Trusted with firm-wide coordination and the details others overlook."],
  }
];

export function secretaryById(id: SecretaryId): SecretaryDefinition {
  const found = SECRETARIES.find((entry) => entry.id === id);
  if (!found) {
    throw new Error(`Unknown secretary id: ${id}`);
  }
  return found;
}

export const SECRETARY_IDS: SecretaryId[] = SECRETARIES.map((entry) => entry.id);
