/** Auto-generated by scripts/build-structure-balance.mjs — do not edit. */
/** Build duration: column C is Excel time (day fraction); buildTimeHours = C × 24 (real-time hours). */

import type { StructureId } from "./types";

export type StructureEffectKind =
  | "cash_per_hour"
  | "supply_per_hour"
  | "connection_per_hour"
  | "mood_per_hour"
  | "cash_holding"
  | "supply_holding"
  | "office_space_bonus"
  | "power_capacity_bonus"
  | "none";

export interface StructureLevelBalanceRow {
  level: number;
  buildTimeHours: number;
  cash: number;
  supply: number;
  connection: number;
  reputation: number;
  govReputation: number;
  electricity: number;
  effect: number;
}

export const STRUCTURE_EFFECT_KIND: Record<StructureId, StructureEffectKind> = {
  "office_desk": "cash_per_hour",
  "bank_account": "cash_holding",
  "office_supply": "supply_per_hour",
  "storage_room": "supply_holding",
  "dept_b2b": "connection_per_hour",
  "break_room": "mood_per_hour",
  "social_media": "connection_per_hour",
  "office_expansion": "office_space_bonus",
  "power_panel": "power_capacity_bonus",
  "dept_rnd": "none",
  "recruitment_desk": "none"
};

export const STRUCTURE_BALANCE_TABLES: Record<
  StructureId,
  StructureLevelBalanceRow[]
> = {
  "office_desk": [
    {
      "level": 1,
      "buildTimeHours": 0,
      "cash": 50,
      "supply": 50,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 5,
      "effect": 200
    },
    {
      "level": 2,
      "buildTimeHours": 0.024,
      "cash": 60,
      "supply": 55,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 5,
      "effect": 250
    },
    {
      "level": 3,
      "buildTimeHours": 0.0264,
      "cash": 72,
      "supply": 60.5,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 5,
      "effect": 312.5
    },
    {
      "level": 4,
      "buildTimeHours": 0.029039999999999996,
      "cash": 86.4,
      "supply": 66.55,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 5,
      "effect": 390.625
    },
    {
      "level": 5,
      "buildTimeHours": 0.1452,
      "cash": 432,
      "supply": 73.205,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 10,
      "effect": 781.25
    },
    {
      "level": 6,
      "buildTimeHours": 0.17424,
      "cash": 518.4,
      "supply": 80.5255,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 10,
      "effect": 976.5625
    },
    {
      "level": 7,
      "buildTimeHours": 0.209088,
      "cash": 622.08,
      "supply": 88.57805,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 10,
      "effect": 1220.703125
    },
    {
      "level": 8,
      "buildTimeHours": 0.2509056,
      "cash": 746.496,
      "supply": 97.435855,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 10,
      "effect": 1525.878906
    },
    {
      "level": 9,
      "buildTimeHours": 0.30108672000000003,
      "cash": 895.7952,
      "supply": 107.1794405,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 10,
      "effect": 1907.348633
    },
    {
      "level": 10,
      "buildTimeHours": 1.2043468800000001,
      "cash": 4478.976,
      "supply": 117.8973846,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 20,
      "effect": 3814.697266
    },
    {
      "level": 11,
      "buildTimeHours": 1.445216256,
      "cash": 5374.7712,
      "supply": 129.687123,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 20,
      "effect": 4577.636719
    },
    {
      "level": 12,
      "buildTimeHours": 1.7342595072,
      "cash": 6449.72544,
      "supply": 142.6558353,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 20,
      "effect": 5493.164063
    },
    {
      "level": 13,
      "buildTimeHours": 2.08111140864,
      "cash": 7739.670528,
      "supply": 156.9214188,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 20,
      "effect": 6591.796875
    },
    {
      "level": 14,
      "buildTimeHours": 2.4973336896,
      "cash": 9287.604634,
      "supply": 172.6135607,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 20,
      "effect": 7910.15625
    },
    {
      "level": 15,
      "buildTimeHours": 6.2433342264,
      "cash": 46438.02317,
      "supply": 189.8749168,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 40,
      "effect": 15820.3125
    },
    {
      "level": 16,
      "buildTimeHours": 7.492001071200001,
      "cash": 55725.6278,
      "supply": 208.8624085,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 40,
      "effect": 17402.34375
    },
    {
      "level": 17,
      "buildTimeHours": 8.9904012864,
      "cash": 66870.75336,
      "supply": 229.7486493,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 40,
      "effect": 19142.57813
    },
    {
      "level": 18,
      "buildTimeHours": 10.7884815432,
      "cash": 80244.90403,
      "supply": 252.7235142,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 40,
      "effect": 21056.83594
    },
    {
      "level": 19,
      "buildTimeHours": 12.946177850399998,
      "cash": 96293.88484,
      "supply": 277.9958657,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 40,
      "effect": 23162.51953
    },
    {
      "level": 20,
      "buildTimeHours": 25.892355695999996,
      "cash": 481469.4242,
      "supply": 305.7954522,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 80,
      "effect": 46325.03906
    }
  ],
  "bank_account": [
    {
      "level": 1,
      "buildTimeHours": 0.0038888888888888888,
      "cash": 60,
      "supply": 80,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 5,
      "effect": 50000
    },
    {
      "level": 2,
      "buildTimeHours": 0.0077777777784,
      "cash": 96,
      "supply": 118.4,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 5,
      "effect": 62500
    },
    {
      "level": 3,
      "buildTimeHours": 0.0155555555544,
      "cash": 153.6,
      "supply": 175.232,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 5,
      "effect": 78125
    },
    {
      "level": 4,
      "buildTimeHours": 0.031111111104,
      "cash": 245.76,
      "supply": 259.34336,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 5,
      "effect": 97656.25
    },
    {
      "level": 5,
      "buildTimeHours": 0.155555555544,
      "cash": 614.4,
      "supply": 383.8281728,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 10,
      "effect": 195312.5
    },
    {
      "level": 6,
      "buildTimeHours": 0.186666666672,
      "cash": 835.584,
      "supply": 671.6993024,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 10,
      "effect": 244140.625
    },
    {
      "level": 7,
      "buildTimeHours": 0.223999999992,
      "cash": 1136.39424,
      "supply": 945.7526178,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 10,
      "effect": 305175.7813
    },
    {
      "level": 8,
      "buildTimeHours": 0.2688,
      "cash": 1545.496166,
      "supply": 1331.619686,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 10,
      "effect": 381469.7266
    },
    {
      "level": 9,
      "buildTimeHours": 0.32256,
      "cash": 2101.874786,
      "supply": 1874.920518,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 10,
      "effect": 476837.1582
    },
    {
      "level": 10,
      "buildTimeHours": 1.29024,
      "cash": 4624.12453,
      "supply": 2639.888089,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 20,
      "effect": 953674.3164
    },
    {
      "level": 11,
      "buildTimeHours": 1.5482879999999999,
      "cash": 6288.809361,
      "supply": 4382.214228,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 20,
      "effect": 1144409.18
    },
    {
      "level": 12,
      "buildTimeHours": 1.8579455999999999,
      "cash": 8552.78073,
      "supply": 6170.157632,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 20,
      "effect": 1373291.016
    },
    {
      "level": 13,
      "buildTimeHours": 2.22953472,
      "cash": 11631.78179,
      "supply": 8687.581946,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 20,
      "effect": 1647949.219
    },
    {
      "level": 14,
      "buildTimeHours": 2.675441664,
      "cash": 15819.22324,
      "supply": 12232.11538,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 20,
      "effect": 1977539.063
    },
    {
      "level": 15,
      "buildTimeHours": 6.688604160000001,
      "cash": 27683.64067,
      "supply": 17222.81846,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 40,
      "effect": 3955078.125
    },
    {
      "level": 16,
      "buildTimeHours": 8.026324992,
      "cash": 37649.75131,
      "supply": 26264.79814,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 40,
      "effect": 4350585.938
    },
    {
      "level": 17,
      "buildTimeHours": 9.6315899904,
      "cash": 51203.66178,
      "supply": 36980.83579,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 40,
      "effect": 4785644.531
    },
    {
      "level": 18,
      "buildTimeHours": 11.557907988,
      "cash": 69636.98002,
      "supply": 52069.01679,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 40,
      "effect": 5264208.984
    },
    {
      "level": 19,
      "buildTimeHours": 13.8694895856,
      "cash": 94706.29283,
      "supply": 73313.17564,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 40,
      "effect": 5790629.883
    },
    {
      "level": 20,
      "buildTimeHours": 27.738979176,
      "cash": 151530.0685,
      "supply": 103224.9513,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 80,
      "effect": 6369692.871
    }
  ],
  "office_supply": [
    {
      "level": 1,
      "buildTimeHours": 0,
      "cash": 50,
      "supply": 50,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 2,
      "effect": 80
    },
    {
      "level": 2,
      "buildTimeHours": 0,
      "cash": 55,
      "supply": 60,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 2,
      "effect": 100
    },
    {
      "level": 3,
      "buildTimeHours": 0,
      "cash": 60.5,
      "supply": 72,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 2,
      "effect": 125
    },
    {
      "level": 4,
      "buildTimeHours": 0,
      "cash": 66.55,
      "supply": 86.4,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 2,
      "effect": 156.25
    },
    {
      "level": 5,
      "buildTimeHours": 0,
      "cash": 73.205,
      "supply": 103.68,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 4,
      "effect": 312.5
    },
    {
      "level": 6,
      "buildTimeHours": 0,
      "cash": 80.5255,
      "supply": 124.416,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 4,
      "effect": 390.625
    },
    {
      "level": 7,
      "buildTimeHours": 0,
      "cash": 88.57805,
      "supply": 149.2992,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 4,
      "effect": 488.28125
    },
    {
      "level": 8,
      "buildTimeHours": 0,
      "cash": 97.435855,
      "supply": 179.15904,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 4,
      "effect": 610.3515625
    },
    {
      "level": 9,
      "buildTimeHours": 0,
      "cash": 107.1794405,
      "supply": 214.990848,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 4,
      "effect": 762.9394531
    },
    {
      "level": 10,
      "buildTimeHours": 0,
      "cash": 117.8973846,
      "supply": 257.9890176,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 8,
      "effect": 1525.878906
    },
    {
      "level": 11,
      "buildTimeHours": 0,
      "cash": 129.687123,
      "supply": 309.5868211,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 8,
      "effect": 1831.054688
    },
    {
      "level": 12,
      "buildTimeHours": 0,
      "cash": 142.6558353,
      "supply": 371.5041853,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 8,
      "effect": 2197.265625
    },
    {
      "level": 13,
      "buildTimeHours": 0,
      "cash": 156.9214188,
      "supply": 445.8050224,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 8,
      "effect": 2636.71875
    },
    {
      "level": 14,
      "buildTimeHours": 0,
      "cash": 172.6135607,
      "supply": 534.9660269,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 8,
      "effect": 3164.0625
    },
    {
      "level": 15,
      "buildTimeHours": 0,
      "cash": 189.8749168,
      "supply": 641.9592323,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 16,
      "effect": 6328.125
    },
    {
      "level": 16,
      "buildTimeHours": 0,
      "cash": 208.8624085,
      "supply": 770.3510787,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 16,
      "effect": 6960.9375
    },
    {
      "level": 17,
      "buildTimeHours": 0,
      "cash": 229.7486493,
      "supply": 924.4212945,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 16,
      "effect": 7657.03125
    },
    {
      "level": 18,
      "buildTimeHours": 0,
      "cash": 252.7235142,
      "supply": 1109.305553,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 16,
      "effect": 8422.734375
    },
    {
      "level": 19,
      "buildTimeHours": 0,
      "cash": 277.9958657,
      "supply": 1331.166664,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 16,
      "effect": 9265.007813
    },
    {
      "level": 20,
      "buildTimeHours": 0,
      "cash": 305.7954522,
      "supply": 1597.399997,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 32,
      "effect": 10191.50859
    }
  ],
  "storage_room": [
    {
      "level": 1,
      "buildTimeHours": 0.0038888888888888888,
      "cash": 260,
      "supply": 180,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 2,
      "effect": 2000
    },
    {
      "level": 2,
      "buildTimeHours": 0.0077777777784,
      "cash": 416,
      "supply": 266.4,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 2,
      "effect": 2500
    },
    {
      "level": 3,
      "buildTimeHours": 0.0155555555544,
      "cash": 665.6,
      "supply": 394.272,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 2,
      "effect": 3125
    },
    {
      "level": 4,
      "buildTimeHours": 0.031111111104,
      "cash": 1064.96,
      "supply": 583.52256,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 2,
      "effect": 3906.25
    },
    {
      "level": 5,
      "buildTimeHours": 0.155555555544,
      "cash": 2662.4,
      "supply": 863.6133888,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 4,
      "effect": 7812.5
    },
    {
      "level": 6,
      "buildTimeHours": 0.186666666672,
      "cash": 3620.864,
      "supply": 1511.32343,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 4,
      "effect": 9765.625
    },
    {
      "level": 7,
      "buildTimeHours": 0.223999999992,
      "cash": 4924.37504,
      "supply": 2127.94339,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 4,
      "effect": 12207.03125
    },
    {
      "level": 8,
      "buildTimeHours": 0.2688,
      "cash": 6697.150054,
      "supply": 2996.144293,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 4,
      "effect": 15258.78906
    },
    {
      "level": 9,
      "buildTimeHours": 0.32256,
      "cash": 9108.124074,
      "supply": 4218.571165,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 4,
      "effect": 19073.48633
    },
    {
      "level": 10,
      "buildTimeHours": 1.29024,
      "cash": 20037.87296,
      "supply": 5939.7482,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 8,
      "effect": 38146.97266
    },
    {
      "level": 11,
      "buildTimeHours": 1.5482879999999999,
      "cash": 27251.50723,
      "supply": 9859.982012,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 8,
      "effect": 45776.36719
    },
    {
      "level": 12,
      "buildTimeHours": 1.8579455999999999,
      "cash": 37062.04983,
      "supply": 13882.85467,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 8,
      "effect": 54931.64063
    },
    {
      "level": 13,
      "buildTimeHours": 2.22953472,
      "cash": 50404.38777,
      "supply": 19547.05938,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 8,
      "effect": 65917.96875
    },
    {
      "level": 14,
      "buildTimeHours": 2.675441664,
      "cash": 68549.96737,
      "supply": 27522.25961,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 8,
      "effect": 79101.5625
    },
    {
      "level": 15,
      "buildTimeHours": 6.688604160000001,
      "cash": 119962.4429,
      "supply": 38751.34153,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 16,
      "effect": 158203.125
    },
    {
      "level": 16,
      "buildTimeHours": 8.026324992,
      "cash": 163148.9223,
      "supply": 59095.79583,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 16,
      "effect": 174023.4375
    },
    {
      "level": 17,
      "buildTimeHours": 9.6315899904,
      "cash": 221882.5344,
      "supply": 83206.88052,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 16,
      "effect": 191425.7813
    },
    {
      "level": 18,
      "buildTimeHours": 11.557907988,
      "cash": 301760.2468,
      "supply": 117155.2878,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 16,
      "effect": 210568.3594
    },
    {
      "level": 19,
      "buildTimeHours": 13.8694895856,
      "cash": 410393.9356,
      "supply": 164954.6452,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 16,
      "effect": 231625.1953
    },
    {
      "level": 20,
      "buildTimeHours": 27.738979176,
      "cash": 656630.2969,
      "supply": 232256.1404,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 32,
      "effect": 254787.7148
    }
  ],
  "dept_b2b": [
    {
      "level": 1,
      "buildTimeHours": 0.0007777777777777778,
      "cash": 168,
      "supply": 168,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 3,
      "effect": 15
    },
    {
      "level": 2,
      "buildTimeHours": 0.00155555555544,
      "cash": 268.8,
      "supply": 248.64,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 3,
      "effect": 18.75
    },
    {
      "level": 3,
      "buildTimeHours": 0.0031111111104000005,
      "cash": 430.08,
      "supply": 367.9872,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 3,
      "effect": 23.4375
    },
    {
      "level": 4,
      "buildTimeHours": 0.0062222222232,
      "cash": 688.128,
      "supply": 544.621056,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 3,
      "effect": 29.2969
    },
    {
      "level": 5,
      "buildTimeHours": 0.031111111104,
      "cash": 1720.32,
      "supply": 806.0391629,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 15,
      "effect": 36.6211
    },
    {
      "level": 6,
      "buildTimeHours": 0.037333333344000005,
      "cash": 2339.6352,
      "supply": 1410.568535,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 15,
      "effect": 45.7764
    },
    {
      "level": 7,
      "buildTimeHours": 0.044800000008,
      "cash": 3181.903872,
      "supply": 1986.080497,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 15,
      "effect": 57.2205
    },
    {
      "level": 8,
      "buildTimeHours": 0.053759999999999995,
      "cash": 4327.389266,
      "supply": 2796.40134,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 15,
      "effect": 71.5256
    },
    {
      "level": 9,
      "buildTimeHours": 0.064512,
      "cash": 5885.249402,
      "supply": 3937.333087,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 15,
      "effect": 89.407
    },
    {
      "level": 10,
      "buildTimeHours": 0.258048,
      "cash": 12947.54868,
      "supply": 5543.764987,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 45,
      "effect": 111.7587
    },
    {
      "level": 11,
      "buildTimeHours": 0.3096576,
      "cash": 17608.66621,
      "supply": 9202.649878,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 45,
      "effect": 139.6984
    },
    {
      "level": 12,
      "buildTimeHours": 0.37158912,
      "cash": 23947.78605,
      "supply": 12957.33103,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 45,
      "effect": 174.623
    },
    {
      "level": 13,
      "buildTimeHours": 0.445906944,
      "cash": 32568.98902,
      "supply": 18243.92209,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 45,
      "effect": 218.2787
    },
    {
      "level": 14,
      "buildTimeHours": 0.5350883328,
      "cash": 44293.82507,
      "supply": 25687.4423,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 45,
      "effect": 272.8484
    },
    {
      "level": 15,
      "buildTimeHours": 1.337720832,
      "cash": 77514.19387,
      "supply": 36167.91876,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 90,
      "effect": 341.0605
    },
    {
      "level": 16,
      "buildTimeHours": 1.6052649984,
      "cash": 105419.3037,
      "supply": 55156.0761,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 90,
      "effect": 426.3256
    },
    {
      "level": 17,
      "buildTimeHours": 1.92631799808,
      "cash": 143370.253,
      "supply": 77659.75515,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 90,
      "effect": 532.9071
    },
    {
      "level": 18,
      "buildTimeHours": 2.3115815976,
      "cash": 194983.5441,
      "supply": 109344.9353,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 90,
      "effect": 666.1338
    },
    {
      "level": 19,
      "buildTimeHours": 2.7738979176000003,
      "cash": 265177.6199,
      "supply": 153957.6688,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 90,
      "effect": 832.6673
    },
    {
      "level": 20,
      "buildTimeHours": 5.5477958352000005,
      "cash": 424284.1919,
      "supply": 216772.3977,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 180,
      "effect": 1040.8341
    }
  ],
  "break_room": [
    {
      "level": 1,
      "buildTimeHours": 0.0016111111111111111,
      "cash": 148,
      "supply": 88,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 3,
      "effect": 25
    },
    {
      "level": 2,
      "buildTimeHours": 0.0032222222232,
      "cash": 236.8,
      "supply": 130.24,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 3,
      "effect": 31.25
    },
    {
      "level": 3,
      "buildTimeHours": 0.0064444444440000005,
      "cash": 378.88,
      "supply": 192.7552,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 3,
      "effect": 39.0625
    },
    {
      "level": 4,
      "buildTimeHours": 0.012888888888000001,
      "cash": 606.208,
      "supply": 285.277696,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 3,
      "effect": 48.8281
    },
    {
      "level": 5,
      "buildTimeHours": 0.06444444444,
      "cash": 1515.52,
      "supply": 422.2109901,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 15,
      "effect": 61.0352
    },
    {
      "level": 6,
      "buildTimeHours": 0.07733333332799999,
      "cash": 2061.1072,
      "supply": 738.8692326,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 15,
      "effect": 76.2939
    },
    {
      "level": 7,
      "buildTimeHours": 0.092800000008,
      "cash": 2803.105792,
      "supply": 1040.32788,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 15,
      "effect": 95.3674
    },
    {
      "level": 8,
      "buildTimeHours": 0.11136,
      "cash": 3812.223877,
      "supply": 1464.781654,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 15,
      "effect": 119.2093
    },
    {
      "level": 9,
      "buildTimeHours": 0.133632,
      "cash": 5184.624473,
      "supply": 2062.412569,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 15,
      "effect": 149.0116
    },
    {
      "level": 10,
      "buildTimeHours": 0.534528,
      "cash": 11406.17384,
      "supply": 2903.876898,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 45,
      "effect": 186.2645
    },
    {
      "level": 11,
      "buildTimeHours": 0.6414336,
      "cash": 15512.39642,
      "supply": 4820.43565,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 45,
      "effect": 232.8306
    },
    {
      "level": 12,
      "buildTimeHours": 0.76972032,
      "cash": 21096.85914,
      "supply": 6787.173396,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 45,
      "effect": 291.0383
    },
    {
      "level": 13,
      "buildTimeHours": 0.923664384,
      "cash": 28691.72842,
      "supply": 9556.340141,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 45,
      "effect": 363.7979
    },
    {
      "level": 14,
      "buildTimeHours": 1.1083972608,
      "cash": 39020.75066,
      "supply": 13455.32692,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 45,
      "effect": 454.7474
    },
    {
      "level": 15,
      "buildTimeHours": 2.770993152,
      "cash": 68286.31365,
      "supply": 18945.1003,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 90,
      "effect": 568.4342
    },
    {
      "level": 16,
      "buildTimeHours": 3.3251917823999997,
      "cash": 92869.38656,
      "supply": 28891.27796,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 90,
      "effect": 710.5427
    },
    {
      "level": 17,
      "buildTimeHours": 3.9902301384,
      "cash": 126302.3657,
      "supply": 40678.91937,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 90,
      "effect": 888.1784
    },
    {
      "level": 18,
      "buildTimeHours": 4.7882761656,
      "cash": 171771.2174,
      "supply": 57275.91847,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 90,
      "effect": 1110.223
    },
    {
      "level": 19,
      "buildTimeHours": 5.7459313992,
      "cash": 233608.8556,
      "supply": 80644.4932,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 90,
      "effect": 1387.7788
    },
    {
      "level": 20,
      "buildTimeHours": 11.4918628008,
      "cash": 373774.169,
      "supply": 113547.4464,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 180,
      "effect": 1734.7235
    }
  ],
  "social_media": [
    {
      "level": 1,
      "buildTimeHours": 0.0016111111111111111,
      "cash": 129,
      "supply": 65,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 3,
      "effect": 8
    },
    {
      "level": 2,
      "buildTimeHours": 0.0032222222232,
      "cash": 206.4,
      "supply": 96.2,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 3,
      "effect": 10
    },
    {
      "level": 3,
      "buildTimeHours": 0.0064444444440000005,
      "cash": 330.24,
      "supply": 142.376,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 3,
      "effect": 12.5
    },
    {
      "level": 4,
      "buildTimeHours": 0.012888888888000001,
      "cash": 528.384,
      "supply": 210.71648,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 3,
      "effect": 15.625
    },
    {
      "level": 5,
      "buildTimeHours": 0.06444444444,
      "cash": 1320.96,
      "supply": 311.8603904,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 15,
      "effect": 19.5313
    },
    {
      "level": 6,
      "buildTimeHours": 0.07733333332799999,
      "cash": 1796.5056,
      "supply": 545.7556832,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 15,
      "effect": 24.4141
    },
    {
      "level": 7,
      "buildTimeHours": 0.092800000008,
      "cash": 2443.247616,
      "supply": 768.4240019,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 15,
      "effect": 30.5176
    },
    {
      "level": 8,
      "buildTimeHours": 0.11136,
      "cash": 3322.816758,
      "supply": 1081.940995,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 15,
      "effect": 38.147
    },
    {
      "level": 9,
      "buildTimeHours": 0.133632,
      "cash": 4519.030791,
      "supply": 1523.372921,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 15,
      "effect": 47.6837
    },
    {
      "level": 10,
      "buildTimeHours": 0.534528,
      "cash": 9941.867739,
      "supply": 2144.909072,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 45,
      "effect": 59.6046
    },
    {
      "level": 11,
      "buildTimeHours": 0.6414336,
      "cash": 13520.94013,
      "supply": 3560.54906,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 45,
      "effect": 74.5058
    },
    {
      "level": 12,
      "buildTimeHours": 0.76972032,
      "cash": 18388.47857,
      "supply": 5013.253076,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 45,
      "effect": 93.1323
    },
    {
      "level": 13,
      "buildTimeHours": 0.923664384,
      "cash": 25008.33086,
      "supply": 7058.660331,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 45,
      "effect": 116.4153
    },
    {
      "level": 14,
      "buildTimeHours": 1.1083972608,
      "cash": 34011.32996,
      "supply": 9938.593747,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 45,
      "effect": 145.5192
    },
    {
      "level": 15,
      "buildTimeHours": 2.770993152,
      "cash": 59519.82744,
      "supply": 13993.54,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 90,
      "effect": 181.8989
    },
    {
      "level": 16,
      "buildTimeHours": 3.3251917823999997,
      "cash": 80946.96531,
      "supply": 21340.14849,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 90,
      "effect": 227.3737
    },
    {
      "level": 17,
      "buildTimeHours": 3.9902301384,
      "cash": 110087.8728,
      "supply": 30046.92908,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 90,
      "effect": 284.2171
    },
    {
      "level": 18,
      "buildTimeHours": 4.7882761656,
      "cash": 149719.507,
      "supply": 42306.07614,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 90,
      "effect": 355.2714
    },
    {
      "level": 19,
      "buildTimeHours": 5.7459313992,
      "cash": 203618.5296,
      "supply": 59566.95521,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 90,
      "effect": 444.0892
    },
    {
      "level": 20,
      "buildTimeHours": 11.4918628008,
      "cash": 325789.6473,
      "supply": 83870.27293,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 180,
      "effect": 555.1115
    }
  ],
  "office_expansion": [
    {
      "level": 1,
      "buildTimeHours": 0.0038888888888888888,
      "cash": 60,
      "supply": 180,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 2,
      "effect": 1
    },
    {
      "level": 2,
      "buildTimeHours": 0.0077777777784,
      "cash": 96,
      "supply": 266.4,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 2,
      "effect": 1
    },
    {
      "level": 3,
      "buildTimeHours": 0.0155555555544,
      "cash": 153.6,
      "supply": 394.272,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 2,
      "effect": 1
    },
    {
      "level": 4,
      "buildTimeHours": 0.031111111104,
      "cash": 245.76,
      "supply": 583.52256,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 2,
      "effect": 1
    },
    {
      "level": 5,
      "buildTimeHours": 0.155555555544,
      "cash": 614.4,
      "supply": 863.6133888,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 4,
      "effect": 1
    },
    {
      "level": 6,
      "buildTimeHours": 0.186666666672,
      "cash": 835.584,
      "supply": 1511.32343,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 4,
      "effect": 1
    },
    {
      "level": 7,
      "buildTimeHours": 0.223999999992,
      "cash": 1136.39424,
      "supply": 2127.94339,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 4,
      "effect": 1
    },
    {
      "level": 8,
      "buildTimeHours": 0.2688,
      "cash": 1545.496166,
      "supply": 2996.144293,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 4,
      "effect": 1
    },
    {
      "level": 9,
      "buildTimeHours": 0.32256,
      "cash": 2101.874786,
      "supply": 4218.571165,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 4,
      "effect": 1
    },
    {
      "level": 10,
      "buildTimeHours": 1.29024,
      "cash": 4624.12453,
      "supply": 5939.7482,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 8,
      "effect": 1
    },
    {
      "level": 11,
      "buildTimeHours": 1.5482879999999999,
      "cash": 6288.809361,
      "supply": 9859.982012,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 8,
      "effect": 1
    },
    {
      "level": 12,
      "buildTimeHours": 1.8579455999999999,
      "cash": 8552.78073,
      "supply": 13882.85467,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 8,
      "effect": 1
    },
    {
      "level": 13,
      "buildTimeHours": 2.22953472,
      "cash": 11631.78179,
      "supply": 19547.05938,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 8,
      "effect": 1
    },
    {
      "level": 14,
      "buildTimeHours": 2.675441664,
      "cash": 15819.22324,
      "supply": 27522.25961,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 8,
      "effect": 1
    },
    {
      "level": 15,
      "buildTimeHours": 6.688604160000001,
      "cash": 27683.64067,
      "supply": 38751.34153,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 16,
      "effect": 1
    },
    {
      "level": 16,
      "buildTimeHours": 8.026324992,
      "cash": 37649.75131,
      "supply": 59095.79583,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 16,
      "effect": 1
    },
    {
      "level": 17,
      "buildTimeHours": 9.6315899904,
      "cash": 51203.66178,
      "supply": 83206.88052,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 16,
      "effect": 1
    },
    {
      "level": 18,
      "buildTimeHours": 11.557907988,
      "cash": 69636.98002,
      "supply": 117155.2878,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 16,
      "effect": 1
    },
    {
      "level": 19,
      "buildTimeHours": 13.8694895856,
      "cash": 94706.29283,
      "supply": 164954.6452,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 16,
      "effect": 1
    },
    {
      "level": 20,
      "buildTimeHours": 27.738979176,
      "cash": 151530.0685,
      "supply": 232256.1404,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 32,
      "effect": 1
    }
  ],
  "power_panel": [
    {
      "level": 1,
      "buildTimeHours": 0.0011111111111111111,
      "cash": 120,
      "supply": 30,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 30
    },
    {
      "level": 2,
      "buildTimeHours": 0.00222222222216,
      "cash": 192,
      "supply": 44.4,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 31.5
    },
    {
      "level": 3,
      "buildTimeHours": 0.0044444444448,
      "cash": 307.2,
      "supply": 65.712,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 33.075
    },
    {
      "level": 4,
      "buildTimeHours": 0.0088888888896,
      "cash": 491.52,
      "supply": 97.25376,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 34.72875
    },
    {
      "level": 5,
      "buildTimeHours": 0.044444444448,
      "cash": 1228.8,
      "supply": 143.9355648,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 69.4575
    },
    {
      "level": 6,
      "buildTimeHours": 0.053333333328,
      "cash": 1671.168,
      "supply": 251.8872384,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 72.930375
    },
    {
      "level": 7,
      "buildTimeHours": 0.064000000008,
      "cash": 2272.78848,
      "supply": 354.6572317,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 76.57689375
    },
    {
      "level": 8,
      "buildTimeHours": 0.07680000000000001,
      "cash": 3090.992333,
      "supply": 499.3573822,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 80.40573844
    },
    {
      "level": 9,
      "buildTimeHours": 0.09216,
      "cash": 4203.749573,
      "supply": 703.0951941,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 84.42602536
    },
    {
      "level": 10,
      "buildTimeHours": 0.36864,
      "cash": 9248.24906,
      "supply": 989.9580333,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 168.8520507
    },
    {
      "level": 11,
      "buildTimeHours": 0.442368,
      "cash": 12577.61872,
      "supply": 1643.330335,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 177.2946533
    },
    {
      "level": 12,
      "buildTimeHours": 0.5308416,
      "cash": 17105.56146,
      "supply": 2313.809112,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 186.1593859
    },
    {
      "level": 13,
      "buildTimeHours": 0.63700992,
      "cash": 23263.56359,
      "supply": 3257.84323,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 195.4673552
    },
    {
      "level": 14,
      "buildTimeHours": 0.7644119039999999,
      "cash": 31638.44648,
      "supply": 4587.043268,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 205.240723
    },
    {
      "level": 15,
      "buildTimeHours": 1.91102976,
      "cash": 55367.28134,
      "supply": 6458.556921,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 410.4814459
    },
    {
      "level": 16,
      "buildTimeHours": 2.293235712,
      "cash": 75299.50262,
      "supply": 9849.299304,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 431.0055182
    },
    {
      "level": 17,
      "buildTimeHours": 2.7518828544,
      "cash": 102407.3236,
      "supply": 13867.81342,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 452.5557942
    },
    {
      "level": 18,
      "buildTimeHours": 3.3022594248,
      "cash": 139273.96,
      "supply": 19525.8813,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 475.1835839
    },
    {
      "level": 19,
      "buildTimeHours": 3.9627113111999996,
      "cash": 189412.5857,
      "supply": 27492.44086,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 498.9427631
    },
    {
      "level": 20,
      "buildTimeHours": 7.925422619999999,
      "cash": 303060.1371,
      "supply": 38709.35674,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 997.8855261
    }
  ],
  "dept_rnd": [
    {
      "level": 1,
      "buildTimeHours": 0.0028888888888888888,
      "cash": 1230,
      "supply": 950,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 5,
      "effect": 0
    },
    {
      "level": 2,
      "buildTimeHours": 0.005777777776800001,
      "cash": 1968,
      "supply": 1406,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 5,
      "effect": 0
    },
    {
      "level": 3,
      "buildTimeHours": 0.011555555556,
      "cash": 3148.8,
      "supply": 2080.88,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 5,
      "effect": 0
    },
    {
      "level": 4,
      "buildTimeHours": 0.023111111112,
      "cash": 5038.08,
      "supply": 3079.7024,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 5,
      "effect": 0
    },
    {
      "level": 5,
      "buildTimeHours": 0.11555555556000001,
      "cash": 12595.2,
      "supply": 4557.959552,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 25,
      "effect": 0
    },
    {
      "level": 6,
      "buildTimeHours": 0.138666666672,
      "cash": 17129.472,
      "supply": 7976.429216,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 25,
      "effect": 0
    },
    {
      "level": 7,
      "buildTimeHours": 0.166399999992,
      "cash": 23296.08192,
      "supply": 11230.81234,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 25,
      "effect": 0
    },
    {
      "level": 8,
      "buildTimeHours": 0.19967999999999997,
      "cash": 31682.67141,
      "supply": 15812.98377,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 25,
      "effect": 0
    },
    {
      "level": 9,
      "buildTimeHours": 0.239616,
      "cash": 43088.43312,
      "supply": 22264.68115,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 25,
      "effect": 0
    },
    {
      "level": 10,
      "buildTimeHours": 0.958464,
      "cash": 94794.55286,
      "supply": 31348.67106,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 75,
      "effect": 0
    }
  ],
  "recruitment_desk": [
    {
      "level": 1,
      "buildTimeHours": 0.0028888888888888888,
      "cash": 500,
      "supply": 1000,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 5,
      "effect": 0
    },
    {
      "level": 2,
      "buildTimeHours": 0.005777777776800001,
      "cash": 800,
      "supply": 1480,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 5,
      "effect": 0
    },
    {
      "level": 3,
      "buildTimeHours": 0.011555555556,
      "cash": 1280,
      "supply": 2190.4,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 5,
      "effect": 0
    },
    {
      "level": 4,
      "buildTimeHours": 0.023111111112,
      "cash": 2048,
      "supply": 3241.792,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 5,
      "effect": 0
    },
    {
      "level": 5,
      "buildTimeHours": 0.11555555556000001,
      "cash": 5120,
      "supply": 4797.85216,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 25,
      "effect": 0
    },
    {
      "level": 6,
      "buildTimeHours": 0.138666666672,
      "cash": 6963.2,
      "supply": 8396.24128,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 25,
      "effect": 0
    },
    {
      "level": 7,
      "buildTimeHours": 0.166399999992,
      "cash": 9469.952,
      "supply": 11821.90772,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 25,
      "effect": 0
    },
    {
      "level": 8,
      "buildTimeHours": 0.19967999999999997,
      "cash": 12879.13472,
      "supply": 16645.24607,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 25,
      "effect": 0
    },
    {
      "level": 9,
      "buildTimeHours": 0.239616,
      "cash": 17515.62322,
      "supply": 23436.50647,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 25,
      "effect": 0
    },
    {
      "level": 10,
      "buildTimeHours": 0.958464,
      "cash": 38534.37108,
      "supply": 32998.60111,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 75,
      "effect": 0
    }
  ]
};
