/** Auto-generated by scripts/build-structure-balance.mjs — do not edit. */
/** Build duration: column C is Excel time (day fraction); buildTimeHours = C × 24 (real-time hours). */

import type { StructureId } from "./types";

export type StructureEffectKind =
  | "cash_per_hour"
  | "supply_per_hour"
  | "connection_per_hour"
  | "mood_per_hour"
  | "cash_holding"
  | "supply_holding"
  | "office_space_bonus"
  | "power_capacity_bonus"
  | "none";

export interface StructureLevelBalanceRow {
  level: number;
  buildTimeHours: number;
  cash: number;
  supply: number;
  connection: number;
  reputation: number;
  govReputation: number;
  electricity: number;
  effect: number;
}

export const STRUCTURE_EFFECT_KIND: Record<StructureId, StructureEffectKind> = {
  "office_desk": "cash_per_hour",
  "bank_account": "cash_holding",
  "office_supply": "supply_per_hour",
  "storage_room": "supply_holding",
  "dept_b2b": "connection_per_hour",
  "break_room": "mood_per_hour",
  "social_media": "connection_per_hour",
  "office_expansion": "office_space_bonus",
  "power_panel": "power_capacity_bonus",
  "recruitment_desk": "none"
};

export const STRUCTURE_BALANCE_TABLES: Record<
  StructureId,
  StructureLevelBalanceRow[]
> = {
  "office_desk": [
    {
      "level": 1,
      "buildTimeHours": 0,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 5,
      "effect": 200
    },
    {
      "level": 2,
      "buildTimeHours": 0.024,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 6,
      "effect": 250
    },
    {
      "level": 3,
      "buildTimeHours": 0.0264,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 8,
      "effect": 312.5
    },
    {
      "level": 4,
      "buildTimeHours": 0.029040000000000003,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 10,
      "effect": 390.625
    },
    {
      "level": 5,
      "buildTimeHours": 0.14520000000000002,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 20,
      "effect": 781.25
    },
    {
      "level": 6,
      "buildTimeHours": 0.17424,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 22,
      "effect": 976.5625
    },
    {
      "level": 7,
      "buildTimeHours": 0.20908800000000002,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 25,
      "effect": 1220.703125
    },
    {
      "level": 8,
      "buildTimeHours": 0.2509056,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 28,
      "effect": 1525.87890625
    },
    {
      "level": 9,
      "buildTimeHours": 0.30108672000000003,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 31,
      "effect": 1907.3486328125
    },
    {
      "level": 10,
      "buildTimeHours": 1.2043468800000001,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 62,
      "effect": 3814.697265625
    },
    {
      "level": 11,
      "buildTimeHours": 1.445216256,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 75,
      "effect": 4577.63671875
    },
    {
      "level": 12,
      "buildTimeHours": 1.7342595071999998,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 83,
      "effect": 5493.1640625
    },
    {
      "level": 13,
      "buildTimeHours": 2.0811114086399995,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 92,
      "effect": 6591.796875
    },
    {
      "level": 14,
      "buildTimeHours": 2.4973336903679995,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 102,
      "effect": 7910.15625
    },
    {
      "level": 15,
      "buildTimeHours": 6.243334225919998,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 204,
      "effect": 15820.3125
    },
    {
      "level": 16,
      "buildTimeHours": 7.492001071103998,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 225,
      "effect": 17402.34375
    },
    {
      "level": 17,
      "buildTimeHours": 8.990401285324799,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 248,
      "effect": 19142.578125
    },
    {
      "level": 18,
      "buildTimeHours": 10.788481542389757,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 273,
      "effect": 21056.8359375
    },
    {
      "level": 19,
      "buildTimeHours": 12.94617785086771,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 301,
      "effect": 23162.519531250004
    },
    {
      "level": 20,
      "buildTimeHours": 25.89235570173542,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 602,
      "effect": 25478.771484375007
    }
  ],
  "bank_account": [
    {
      "level": 1,
      "buildTimeHours": 0,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 50000
    },
    {
      "level": 2,
      "buildTimeHours": 0.024,
      "cash": 100,
      "supply": 50,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 62500
    },
    {
      "level": 3,
      "buildTimeHours": 0.048,
      "cash": 160,
      "supply": 80,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 78125
    },
    {
      "level": 4,
      "buildTimeHours": 0.096,
      "cash": 256,
      "supply": 128,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 97656.25
    },
    {
      "level": 5,
      "buildTimeHours": 0.48,
      "cash": 640,
      "supply": 320,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 195312.5
    },
    {
      "level": 6,
      "buildTimeHours": 0.5760000000000001,
      "cash": 870.3999999999999,
      "supply": 435.19999999999993,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 244140.625
    },
    {
      "level": 7,
      "buildTimeHours": 0.6912,
      "cash": 1183.7439999999997,
      "supply": 591.8719999999998,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 305175.78125
    },
    {
      "level": 8,
      "buildTimeHours": 0.82944,
      "cash": 1609.8918399999993,
      "supply": 804.9459199999997,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 381469.7265625
    },
    {
      "level": 9,
      "buildTimeHours": 0.995328,
      "cash": 2189.452902399999,
      "supply": 1094.7264511999995,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 476837.158203125
    },
    {
      "level": 10,
      "buildTimeHours": 3.981312,
      "cash": 4816.7963852799985,
      "supply": 2408.3981926399993,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 953674.31640625
    },
    {
      "level": 11,
      "buildTimeHours": 4.777574400000001,
      "cash": 6550.843083980797,
      "supply": 3275.4215419903985,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 1144409.1796875
    },
    {
      "level": 12,
      "buildTimeHours": 5.73308928,
      "cash": 8909.146594213884,
      "supply": 4454.573297106942,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 1373291.015625
    },
    {
      "level": 13,
      "buildTimeHours": 6.879707136,
      "cash": 12116.439368130881,
      "supply": 6058.219684065441,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 1647949.21875
    },
    {
      "level": 14,
      "buildTimeHours": 8.2556485632,
      "cash": 16478.357540658,
      "supply": 8239.178770329,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 1977539.0625
    },
    {
      "level": 15,
      "buildTimeHours": 20.639121407999998,
      "cash": 28837.125696151496,
      "supply": 14418.562848075748,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 3955078.125
    },
    {
      "level": 16,
      "buildTimeHours": 24.7669456896,
      "cash": 39218.49094676603,
      "supply": 19609.245473383016,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 4350585.9375
    },
    {
      "level": 17,
      "buildTimeHours": 29.72033482752,
      "cash": 53337.1476876018,
      "supply": 26668.5738438009,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 4785644.53125
    },
    {
      "level": 18,
      "buildTimeHours": 35.66440179302399,
      "cash": 72538.52085513844,
      "supply": 36269.26042756922,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 5264208.984375
    },
    {
      "level": 19,
      "buildTimeHours": 42.79728215162879,
      "cash": 98652.38836298828,
      "supply": 49326.19418149414,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 5790629.882812501
    },
    {
      "level": 20,
      "buildTimeHours": 85.59456430325758,
      "cash": 157843.82138078124,
      "supply": 78921.91069039062,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 6369692.871093752
    }
  ],
  "office_supply": [
    {
      "level": 1,
      "buildTimeHours": 0,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 2,
      "effect": 80
    },
    {
      "level": 2,
      "buildTimeHours": 0.024,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 3,
      "effect": 100
    },
    {
      "level": 3,
      "buildTimeHours": 0.048,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 4,
      "effect": 125
    },
    {
      "level": 4,
      "buildTimeHours": 0.096,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 5,
      "effect": 156.25
    },
    {
      "level": 5,
      "buildTimeHours": 0.48,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 10,
      "effect": 312.5
    },
    {
      "level": 6,
      "buildTimeHours": 0.5760000000000001,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 13,
      "effect": 390.625
    },
    {
      "level": 7,
      "buildTimeHours": 0.6912,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 17,
      "effect": 488.28125
    },
    {
      "level": 8,
      "buildTimeHours": 0.82944,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 22,
      "effect": 610.3515625
    },
    {
      "level": 9,
      "buildTimeHours": 0.995328,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 28,
      "effect": 762.939453125
    },
    {
      "level": 10,
      "buildTimeHours": 3.981312,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 56,
      "effect": 1525.87890625
    },
    {
      "level": 11,
      "buildTimeHours": 4.777574400000001,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 59,
      "effect": 1831.0546875
    },
    {
      "level": 12,
      "buildTimeHours": 5.73308928,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 62,
      "effect": 2197.265625
    },
    {
      "level": 13,
      "buildTimeHours": 6.879707136,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 66,
      "effect": 2636.71875
    },
    {
      "level": 14,
      "buildTimeHours": 8.2556485632,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 70,
      "effect": 3164.0625
    },
    {
      "level": 15,
      "buildTimeHours": 20.639121407999998,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 140,
      "effect": 6328.125
    },
    {
      "level": 16,
      "buildTimeHours": 24.7669456896,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 147,
      "effect": 6960.937500000001
    },
    {
      "level": 17,
      "buildTimeHours": 29.72033482752,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 155,
      "effect": 7657.031250000002
    },
    {
      "level": 18,
      "buildTimeHours": 35.66440179302399,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 163,
      "effect": 8422.734375000002
    },
    {
      "level": 19,
      "buildTimeHours": 42.79728215162879,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 172,
      "effect": 9265.007812500004
    },
    {
      "level": 20,
      "buildTimeHours": 85.59456430325758,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 190,
      "effect": 10191.508593750004
    }
  ],
  "storage_room": [
    {
      "level": 1,
      "buildTimeHours": 0,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 2,
      "effect": 2000
    },
    {
      "level": 2,
      "buildTimeHours": 0.024,
      "cash": 120,
      "supply": 30,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 2,
      "effect": 2500
    },
    {
      "level": 3,
      "buildTimeHours": 0.048,
      "cash": 192,
      "supply": 44.4,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 2,
      "effect": 3125
    },
    {
      "level": 4,
      "buildTimeHours": 0.096,
      "cash": 307.20000000000005,
      "supply": 65.712,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 2,
      "effect": 3906.25
    },
    {
      "level": 5,
      "buildTimeHours": 0.48,
      "cash": 768.0000000000001,
      "supply": 97.25376,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 10,
      "effect": 7812.5
    },
    {
      "level": 6,
      "buildTimeHours": 0.5760000000000001,
      "cash": 1044.48,
      "supply": 170.19407999999999,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 10,
      "effect": 9765.625
    },
    {
      "level": 7,
      "buildTimeHours": 0.6912,
      "cash": 1420.4928,
      "supply": 239.63326463999996,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 10,
      "effect": 12207.03125
    },
    {
      "level": 8,
      "buildTimeHours": 0.82944,
      "cash": 1931.8702079999998,
      "supply": 337.40363661311994,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 10,
      "effect": 15258.7890625
    },
    {
      "level": 9,
      "buildTimeHours": 0.995328,
      "cash": 2627.3434828799996,
      "supply": 475.06432035127284,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 10,
      "effect": 19073.486328125
    },
    {
      "level": 10,
      "buildTimeHours": 3.981312,
      "cash": 5780.155662335999,
      "supply": 668.8905630545921,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 30,
      "effect": 38146.97265625
    },
    {
      "level": 11,
      "buildTimeHours": 4.777574400000001,
      "cash": 7861.011700776959,
      "supply": 1110.358334670623,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 30,
      "effect": 45776.3671875
    },
    {
      "level": 12,
      "buildTimeHours": 5.73308928,
      "cash": 10690.975913056664,
      "supply": 1563.384535216237,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 30,
      "effect": 54931.640625
    },
    {
      "level": 13,
      "buildTimeHours": 6.879707136,
      "cash": 14539.72724175706,
      "supply": 2201.245425584462,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 30,
      "effect": 65917.96875
    },
    {
      "level": 14,
      "buildTimeHours": 8.2556485632,
      "cash": 19774.0290487896,
      "supply": 3099.3535592229223,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 30,
      "effect": 79101.5625
    },
    {
      "level": 15,
      "buildTimeHours": 20.639121407999998,
      "cash": 34604.5508353818,
      "supply": 4363.889811385874,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 60,
      "effect": 158203.125
    },
    {
      "level": 16,
      "buildTimeHours": 24.7669456896,
      "cash": 47062.18913611925,
      "supply": 6654.931962363457,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 60,
      "effect": 174023.4375
    },
    {
      "level": 17,
      "buildTimeHours": 29.72033482752,
      "cash": 64004.57722512217,
      "supply": 9370.144203007747,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 60,
      "effect": 191425.78125000003
    },
    {
      "level": 18,
      "buildTimeHours": 35.66440179302399,
      "cash": 87046.22502616614,
      "supply": 13193.163037834907,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 60,
      "effect": 210568.35937500006
    },
    {
      "level": 19,
      "buildTimeHours": 42.79728215162879,
      "cash": 118382.86603558593,
      "supply": 18575.973557271547,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 60,
      "effect": 231625.1953125001
    },
    {
      "level": 20,
      "buildTimeHours": 85.59456430325758,
      "cash": 189412.5856569375,
      "supply": 26154.970768638337,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 120,
      "effect": 254787.71484375012
    }
  ],
  "dept_b2b": [
    {
      "level": 1,
      "buildTimeHours": 0,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 5,
      "effect": 15
    },
    {
      "level": 2,
      "buildTimeHours": 0.024,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 6,
      "effect": 18.75
    },
    {
      "level": 3,
      "buildTimeHours": 0.0264,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 8,
      "effect": 23.44
    },
    {
      "level": 4,
      "buildTimeHours": 0.029040000000000003,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 10,
      "effect": 29.3
    },
    {
      "level": 5,
      "buildTimeHours": 0.14520000000000002,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 20,
      "effect": 58.59
    },
    {
      "level": 6,
      "buildTimeHours": 0.17424,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 22,
      "effect": 73.24
    },
    {
      "level": 7,
      "buildTimeHours": 0.20908800000000002,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 25,
      "effect": 91.55
    },
    {
      "level": 8,
      "buildTimeHours": 0.2509056,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 28,
      "effect": 114.44
    },
    {
      "level": 9,
      "buildTimeHours": 0.30108672000000003,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 31,
      "effect": 143.05
    },
    {
      "level": 10,
      "buildTimeHours": 1.2043468800000001,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 62,
      "effect": 286.1
    },
    {
      "level": 11,
      "buildTimeHours": 1.445216256,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 75,
      "effect": 343.32
    },
    {
      "level": 12,
      "buildTimeHours": 1.7342595071999998,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 83,
      "effect": 411.99
    },
    {
      "level": 13,
      "buildTimeHours": 2.0811114086399995,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 92,
      "effect": 494.38
    },
    {
      "level": 14,
      "buildTimeHours": 2.4973336903679995,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 102,
      "effect": 593.26
    },
    {
      "level": 15,
      "buildTimeHours": 6.243334225919998,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 204,
      "effect": 1186.52
    },
    {
      "level": 16,
      "buildTimeHours": 7.492001071103998,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 225,
      "effect": 1305.18
    },
    {
      "level": 17,
      "buildTimeHours": 8.990401285324799,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 248,
      "effect": 1435.69
    },
    {
      "level": 18,
      "buildTimeHours": 10.788481542389757,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 273,
      "effect": 1579.26
    },
    {
      "level": 19,
      "buildTimeHours": 12.94617785086771,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 301,
      "effect": 1737.19
    },
    {
      "level": 20,
      "buildTimeHours": 25.89235570173542,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 602,
      "effect": 1910.91
    }
  ],
  "break_room": [
    {
      "level": 1,
      "buildTimeHours": 0,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 2,
      "effect": 25
    },
    {
      "level": 2,
      "buildTimeHours": 0.024,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 3,
      "effect": 31.25
    },
    {
      "level": 3,
      "buildTimeHours": 0.048,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 4,
      "effect": 39.06
    },
    {
      "level": 4,
      "buildTimeHours": 0.096,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 5,
      "effect": 48.83
    },
    {
      "level": 5,
      "buildTimeHours": 0.48,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 10,
      "effect": 97.66
    },
    {
      "level": 6,
      "buildTimeHours": 0.5760000000000001,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 13,
      "effect": 122.07
    },
    {
      "level": 7,
      "buildTimeHours": 0.6912,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 17,
      "effect": 152.59
    },
    {
      "level": 8,
      "buildTimeHours": 0.82944,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 22,
      "effect": 190.73
    },
    {
      "level": 9,
      "buildTimeHours": 0.995328,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 28,
      "effect": 238.42
    },
    {
      "level": 10,
      "buildTimeHours": 3.981312,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 56,
      "effect": 476.84
    },
    {
      "level": 11,
      "buildTimeHours": 4.777574400000001,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 59,
      "effect": 572.2
    },
    {
      "level": 12,
      "buildTimeHours": 5.73308928,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 62,
      "effect": 686.65
    },
    {
      "level": 13,
      "buildTimeHours": 6.879707136,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 66,
      "effect": 823.97
    },
    {
      "level": 14,
      "buildTimeHours": 8.2556485632,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 70,
      "effect": 988.77
    },
    {
      "level": 15,
      "buildTimeHours": 20.639121407999998,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 140,
      "effect": 1977.54
    },
    {
      "level": 16,
      "buildTimeHours": 24.7669456896,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 147,
      "effect": 2175.29
    },
    {
      "level": 17,
      "buildTimeHours": 29.72033482752,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 155,
      "effect": 2392.82
    },
    {
      "level": 18,
      "buildTimeHours": 35.66440179302399,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 163,
      "effect": 2632.1
    },
    {
      "level": 19,
      "buildTimeHours": 42.79728215162879,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 172,
      "effect": 2895.31
    },
    {
      "level": 20,
      "buildTimeHours": 85.59456430325758,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 190,
      "effect": 3184.85
    }
  ],
  "social_media": [
    {
      "level": 1,
      "buildTimeHours": 0,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 2,
      "effect": 8
    },
    {
      "level": 2,
      "buildTimeHours": 0.024,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 3,
      "effect": 10
    },
    {
      "level": 3,
      "buildTimeHours": 0.048,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 4,
      "effect": 12.5
    },
    {
      "level": 4,
      "buildTimeHours": 0.096,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 5,
      "effect": 15.63
    },
    {
      "level": 5,
      "buildTimeHours": 0.48,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 10,
      "effect": 31.25
    },
    {
      "level": 6,
      "buildTimeHours": 0.5760000000000001,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 13,
      "effect": 39.06
    },
    {
      "level": 7,
      "buildTimeHours": 0.6912,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 17,
      "effect": 48.83
    },
    {
      "level": 8,
      "buildTimeHours": 0.82944,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 22,
      "effect": 61.04
    },
    {
      "level": 9,
      "buildTimeHours": 0.995328,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 28,
      "effect": 76.29
    },
    {
      "level": 10,
      "buildTimeHours": 3.981312,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 56,
      "effect": 152.59
    },
    {
      "level": 11,
      "buildTimeHours": 4.777574400000001,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 59,
      "effect": 183.11
    },
    {
      "level": 12,
      "buildTimeHours": 5.73308928,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 62,
      "effect": 219.73
    },
    {
      "level": 13,
      "buildTimeHours": 6.879707136,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 66,
      "effect": 263.67
    },
    {
      "level": 14,
      "buildTimeHours": 8.2556485632,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 70,
      "effect": 316.41
    },
    {
      "level": 15,
      "buildTimeHours": 20.639121407999998,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 140,
      "effect": 632.81
    },
    {
      "level": 16,
      "buildTimeHours": 24.7669456896,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 147,
      "effect": 696.09
    },
    {
      "level": 17,
      "buildTimeHours": 29.72033482752,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 155,
      "effect": 765.7
    },
    {
      "level": 18,
      "buildTimeHours": 35.66440179302399,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 163,
      "effect": 842.27
    },
    {
      "level": 19,
      "buildTimeHours": 42.79728215162879,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 172,
      "effect": 926.5
    },
    {
      "level": 20,
      "buildTimeHours": 85.59456430325758,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 190,
      "effect": 1019.15
    }
  ],
  "office_expansion": [
    {
      "level": 1,
      "buildTimeHours": 0,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 0
    },
    {
      "level": 2,
      "buildTimeHours": 0.024,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 2
    },
    {
      "level": 3,
      "buildTimeHours": 0.0264,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 4
    },
    {
      "level": 4,
      "buildTimeHours": 0.029040000000000003,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 6
    },
    {
      "level": 5,
      "buildTimeHours": 0.14520000000000002,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 8
    },
    {
      "level": 6,
      "buildTimeHours": 0.17424,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 10
    },
    {
      "level": 7,
      "buildTimeHours": 0.20908800000000002,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 12
    },
    {
      "level": 8,
      "buildTimeHours": 0.2509056,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 14
    },
    {
      "level": 9,
      "buildTimeHours": 0.30108672000000003,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 16
    },
    {
      "level": 10,
      "buildTimeHours": 1.2043468800000001,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 18
    },
    {
      "level": 11,
      "buildTimeHours": 1.445216256,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 20
    },
    {
      "level": 12,
      "buildTimeHours": 1.7342595071999998,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 22
    },
    {
      "level": 13,
      "buildTimeHours": 2.0811114086399995,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 24
    },
    {
      "level": 14,
      "buildTimeHours": 2.4973336903679995,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 26
    },
    {
      "level": 15,
      "buildTimeHours": 6.243334225919998,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 28
    },
    {
      "level": 16,
      "buildTimeHours": 7.492001071103998,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 30
    },
    {
      "level": 17,
      "buildTimeHours": 8.990401285324799,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 32
    },
    {
      "level": 18,
      "buildTimeHours": 10.788481542389757,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 34
    },
    {
      "level": 19,
      "buildTimeHours": 12.94617785086771,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 36
    },
    {
      "level": 20,
      "buildTimeHours": 25.89235570173542,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 38
    }
  ],
  "power_panel": [
    {
      "level": 1,
      "buildTimeHours": 0,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 0
    },
    {
      "level": 2,
      "buildTimeHours": 0.024,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 5
    },
    {
      "level": 3,
      "buildTimeHours": 0.048,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 10
    },
    {
      "level": 4,
      "buildTimeHours": 0.096,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 15
    },
    {
      "level": 5,
      "buildTimeHours": 0.48,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 20
    },
    {
      "level": 6,
      "buildTimeHours": 0.5760000000000001,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 25
    },
    {
      "level": 7,
      "buildTimeHours": 0.6912,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 30
    },
    {
      "level": 8,
      "buildTimeHours": 0.82944,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 35
    },
    {
      "level": 9,
      "buildTimeHours": 0.995328,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 40
    },
    {
      "level": 10,
      "buildTimeHours": 3.981312,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 45
    },
    {
      "level": 11,
      "buildTimeHours": 4.777574400000001,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 50
    },
    {
      "level": 12,
      "buildTimeHours": 5.73308928,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 55
    },
    {
      "level": 13,
      "buildTimeHours": 6.879707136,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 60
    },
    {
      "level": 14,
      "buildTimeHours": 8.2556485632,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 65
    },
    {
      "level": 15,
      "buildTimeHours": 20.639121407999998,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 70
    },
    {
      "level": 16,
      "buildTimeHours": 24.7669456896,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 75
    },
    {
      "level": 17,
      "buildTimeHours": 29.72033482752,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 80
    },
    {
      "level": 18,
      "buildTimeHours": 35.66440179302399,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 85
    },
    {
      "level": 19,
      "buildTimeHours": 42.79728215162879,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 90
    },
    {
      "level": 20,
      "buildTimeHours": 85.59456430325758,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 95
    }
  ],
  "recruitment_desk": [
    {
      "level": 1,
      "buildTimeHours": 0,
      "cash": 0,
      "supply": 0,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 0
    },
    {
      "level": 2,
      "buildTimeHours": 0.024,
      "cash": 100,
      "supply": 50,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 0
    },
    {
      "level": 3,
      "buildTimeHours": 0.048,
      "cash": 160,
      "supply": 80,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 0
    },
    {
      "level": 4,
      "buildTimeHours": 0.096,
      "cash": 256,
      "supply": 128,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 0
    },
    {
      "level": 5,
      "buildTimeHours": 0.48,
      "cash": 640,
      "supply": 320,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 0
    },
    {
      "level": 6,
      "buildTimeHours": 0.5760000000000001,
      "cash": 870.3999999999999,
      "supply": 435.19999999999993,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 0
    },
    {
      "level": 7,
      "buildTimeHours": 0.6912,
      "cash": 1183.7439999999997,
      "supply": 591.8719999999998,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 0
    },
    {
      "level": 8,
      "buildTimeHours": 0.82944,
      "cash": 1609.8918399999993,
      "supply": 804.9459199999997,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 0
    },
    {
      "level": 9,
      "buildTimeHours": 0.995328,
      "cash": 2189.452902399999,
      "supply": 1094.7264511999995,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 0
    },
    {
      "level": 10,
      "buildTimeHours": 3.981312,
      "cash": 4816.7963852799985,
      "supply": 2408.3981926399993,
      "connection": 0,
      "reputation": 0,
      "govReputation": 0,
      "electricity": 0,
      "effect": 0
    }
  ]
};
